# Generated by Django 5.2.1 on 2025-05-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etkinlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=255)),
                ('tarih', models.DateTimeField()),
                ('toplam_bilet', models.IntegerField()),
                ('kalan_bilet', models.IntegerField()),
                ('iptal_mi', models.BooleanField(default=False)),
                ('sehir', models.CharField(max_length=100)),
                ('konum', models.TextField()),
                ('fiyat', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('tur', models.CharField(choices=[('konser', 'Konser'), ('tiyatro', 'Tiyatro'), ('film', 'Film'), ('sergi', 'Sergi'), ('diger', 'Diğer')], default='diger', max_length=20)),
                ('image_url', models.URLField(default='https://via.placeholder.com/300x200.png?text=Etkinlik+Görseli', verbose_name='Etkinlik Görseli')),
            ],
        ),
    ]
