# Generated by Django 5.2.1 on 2025-05-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlik',
            name='ogrenci_fiyat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='vip_fiyat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
