# Generated by Django 5.2.1 on 2025-05-22 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etkinlik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.PositiveIntegerField(default=1)),
                ('etkinlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etkinlik.etkinlik')),
            ],
        ),
    ]
