# Generated by Django 5.2.1 on 2025-05-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepet', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='bilet_turu',
            field=models.CharField(choices=[('standart', 'Standart'), ('vip', 'VIP'), ('ogrenci', 'Öğrenci')], default='standart', max_length=10),
        ),
    ]
