# Generated by Django 5.2.1 on 2025-05-22 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etkinlik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.PositiveIntegerField()),
                ('satin_alma_tarihi', models.DateTimeField(blank=True, null=True)),
                ('toplam_fiyat', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('satin_alindi', models.BooleanField(default=False)),
                ('etkinlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etkinlik.etkinlik')),
            ],
        ),
    ]
